import Header from "@/components/Header";
import Providers from "./providers";
import "@/app/global.css";
import { Manrope } from "next/font/google";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const manrope = Manrope({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={manrope.className}>
      <head />
      <body>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
