import Header from "@/components/Header";
import Providers from "./providers";
import "@/app/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
