import Header from "@/components/Header";
import Providers from "./providers";
import "@/app/global.css";
import { Saira, Inter } from "next/font/google";

import "primereact/resources/themes/saga-green/theme.css"; // ili druga tema po želji
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css"; // ikone

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const saira = Saira({ subsets: ["latin"], variable: "--font-saira" });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={`${saira.variable} ${inter.variable}`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
