import { PricingPlan } from "@/types/types";
import {
  Check,
  X,
  ChevronRight,
  Zap,
  Image,
  Crop,
  Maximize2,
  FileImage,
  FileInput,
  FileOutput,
  Headset,
} from "lucide-react";

export const pricingPlans: PricingPlan[] = [
  {
    id: "free",
    name: "Starter",
    price: 0,
    billing: "forever",
    description: "Basic functionality for beginners",
    features: [
      { text: "Convert (JPG/PNG/WEBP)", icon: Image },
      { text: "Basic crop tool", icon: Crop },
      { text: "Resize up to 1920px", icon: Maximize2 },
      { text: "System watermark added", icon: X, negative: true },
      { text: "Max 3MB per file", icon: ChevronRight },
      { text: "Batch processing (5 files)", icon: FileInput },

      //   { text: "5 daily operations", icon: ChevronRight },
    ],
    cta: {
      text: "Start for free",
      variant: "outlined",
      icon: "pi pi-check-circle",
      severity: "secondary",
    },
    badge: "No card required",
  },
  {
    id: "pro",
    name: "Professional",
    price: 7.99,
    billing: "monthly",
    featured: true,
    description: "For freelancers and creators",
    features: [
      { text: "Everything in Starter plan", icon: Check },
      //   { text: "Custom watermark", icon: Paintbrush },
      { text: "Crop face feature", icon: Headset, premium: true },
      { text: "Collage feature", icon: Headset, premium: true },
      { text: "Batch processing (10 files)", icon: FileInput },
      { text: "AVIF/TIFF/GIF/HEIF support", icon: FileOutput },
      { text: "Max 15MB per file", icon: ChevronRight },
      //   { text: "100 daily operations", icon: ChevronRight },
      { text: "Priority support", icon: Headset, premium: true },
    ],
    cta: {
      text: "Upgrade now",
      variant: "contained",
      icon: "pi pi-star",
      severity: "success",
    },
    ribbon: "BEST VALUE",
    annualDiscount: 15,
  },
  {
    id: "business",
    name: "Business",
    price: 24.99,
    billing: "monthly",
    description: "For teams and agencies",
    features: [
      { text: "Everything in Professional plan", icon: Check },
      //   { text: "API access", icon: Server },
      { text: "White-label solution", icon: FileImage },
      { text: "Dedicated support", icon: Headset },
      { text: "Max 500MB per file", icon: ChevronRight },
      { text: "Unlimited operations", icon: Zap },
      { text: "Batch processing (50 files)", icon: FileInput },

      //   { text: "SSO integrations", icon: Key, premium: true },
    ],
    cta: {
      text: "Contact us",
      variant: "contained",
      icon: "pi pi-send",
      severity: "info",
      disabled: false,
    },
    custom: true,
  },
];
